const assert=require('node:assert/strict');
const Mount=require('../static/door-mount.js');
const Template=require('../static/door-template.js');
const {doorHingeView,doorOpeningView}=require('../static/door-editor.js');
const g={walls:[{id:'w',x1:0,y1:0,x2:100,y2:0,thickness:10}],doors:[{id:'d',wallId:'w',x:50,y:0,width:48,swing:'left',openingSide:-1}]};
const e={hostDoorId:'d',type:'reader',doorMount:{side:1,surface:'wall',offset:35}};
const a=Mount.resolve(e,g),b=Mount.resolve({...e,doorMount:{...e.doorMount,side:-1}},g);
assert.equal(a.x,85);assert.equal(a.y,-b.y);assert.ok(a.y>5);
const leaf={...e,doorMount:{side:1,surface:'leaf',offset:10}};
assert.notEqual(Mount.resolve(leaf,g,true).x,Mount.resolve(leaf,g,false).x);
assert.equal(Mount.resolve(e,g,true).x,a.x);
const moved=structuredClone(g);moved.doors[0].x+=20;
assert.equal(Mount.resolve(e,moved).x,a.x+20);
const items=[];let counter=0;
const touched=Template.apply(items,g.doors[0],1,type=>({id:`e${++counter}`,type,code:type,x:50,y:0}));
assert.equal(touched.length,8);
assert.equal(items.find(item=>item.type==='reader').mountingHeight,1100);
assert.equal(items.find(item=>item.type==='reader').doorMount.side,1);
assert.equal(items.find(item=>item.type==='exit_button').doorMount.side,-1);
assert.equal(items.find(item=>item.type==='emergency_release').mountingHeight,1750);
assert.ok(items.every(item=>item.templateSource.includes('лист 6')));
Template.apply(items,g.doors[0],-1,()=>{throw new Error('Шаблон не должен создавать дубли');});
assert.equal(items.length,8);assert.equal(items.find(item=>item.type==='reader').doorMount.side,-1);
assert.equal(items.find(item=>item.type==='lock').doorMount.surface,'frame');
assert.equal(items.find(item=>item.type==='lock_strike').doorMount.surface,'leaf');
assert.equal(items.find(item=>item.type==='door_closer').doorMount.surface,'leaf');
assert.equal(doorHingeView(g.doors[0],1).label,'Петли слева');
assert.equal(doorHingeView(g.doors[0],-1).label,'Петли справа');
assert.deepEqual(doorHingeView({...g.doors[0],leafCount:2},1).positions,[-24,24]);
assert.equal(doorOpeningView(g.doors[0],-1).label,'НА СЕБЯ · в сторону Б');
assert.equal(doorOpeningView(g.doors[0],1).label,'ОТ СЕБЯ · в сторону Б');
assert.equal(doorOpeningView({...g.doors[0],openingSide:1},1).toward,true);
console.log('PASS: opposing faces, wall clearance, moving leaf and door-relative placement');
