const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const path = require('node:path');
const elements = new Map();
const document = {querySelector(id) {
  if (!elements.has(id)) elements.set(id, {checked:false, classList:{add(){},remove(){},toggle(){}},addEventListener(){}});
  return elements.get(id);
}};
const context = vm.createContext({document, URLSearchParams, location:{search:''}, setTimeout(){}, clearTimeout(){}});
const src = fs.readFileSync(path.join(__dirname,'../static/app-v2.js'),'utf8').replace(/start\(\);\s*$/, '');
vm.runInContext(src + '\nthis.api={state,layers,nearestElement,selectedEditable,handleEditorDown,handleEditorMove,bindCanvasNavigation,addEquipment,addCeilingZone,deleteSelected,cameraVisibilityPolygon,cameraCoverageShape,cameraAutoBlindZone,cameraPlanAngle,normalizeAccessPointCode,projectEquipmentCode,migrateEquipmentCode,assignAccessPointToDoor,accessPointForDoor,accessPointMarkerPosition,equipmentShownOnPlan}; drawGeometry=()=>{};drawEquipment=()=>{};showGeometryCard=()=>{};',context);
const {state,layers,nearestElement,selectedEditable,handleEditorDown,handleEditorMove,bindCanvasNavigation,addEquipment,addCeilingZone,deleteSelected,cameraVisibilityPolygon,cameraCoverageShape,cameraAutoBlindZone,cameraPlanAngle,normalizeAccessPointCode,projectEquipmentCode,migrateEquipmentCode,assignAccessPointToDoor,accessPointForDoor,accessPointMarkerPosition,equipmentShownOnPlan} = context.api;
state.geometry={walls:[{id:'W',type:'wall',x1:0,y1:0,x2:400,y2:0},{id:'W2',type:'wall',x1:0,y1:150,x2:400,y2:150}],doors:[],windows:[{id:'WIN',wallId:'W',x:100,y:0,width:72,rotation:0}]};
assert.equal(nearestElement({x:134,y:0}).kind,'window','Full width of window precedes wall');
layers.window.locked=true;
state.selected={kind:'wall',id:'W'};
assert.equal(selectedEditable(),false,'Host wall cannot move/delete a locked opening');
layers.window.locked=false;
assert.equal(selectedEditable(),true);
layers.wall.locked=true;
assert.equal(nearestElement({x:134,y:0}).kind,'window','Window stays editable on locked wall');
layers.window.visible=false;
assert.equal(nearestElement({x:134,y:0}),null,'Hidden openings cannot be selected');
layers.window.visible=true;
const handlers={};
state.app={canvas:{getBoundingClientRect:()=>({left:0,top:0}),setPointerCapture(){},addEventListener:(name,fn)=>handlers[name]=fn}};
state.world={x:0,y:0,position:{set(x,y){state.world.x=x;state.world.y=y;}}};
state.selected={kind:'window',id:'WIN'};
state.moving={start:{x:100,y:0},started:false,geometry:JSON.parse(JSON.stringify(state.geometry))};
handleEditorMove({clientX:200,clientY:140,altKey:false});
assert.equal(state.geometry.windows[0].wallId,'W','Default drag stays on host');
assert.equal(state.geometry.windows[0].x,200);
handleEditorMove({clientX:220,clientY:150,altKey:true});
assert.equal(state.geometry.windows[0].wallId,'W2','Alt transfers opening');
handleEditorMove({clientX:999,clientY:150,altKey:false});
assert.equal(state.geometry.windows[0].x,364,'Opening clamped within wall');
state.moving=null;
state.editorEnabled=true;state.tool='pan';
bindCanvasNavigation();
const before=JSON.stringify(state.geometry);
handlers.pointerdown({clientX:10,clientY:20,pointerId:1,button:0});
handlers.pointermove({clientX:60,clientY:90});
assert.equal(state.world.x,50);assert.equal(state.world.y,70);
handlers.pointerup();
assert.equal(state.dragging,false);
assert.equal(JSON.stringify(state.geometry),before,'Pan never changes geometry');
console.log('PASS: window priority, locks, host projection, Alt transfer, edge clamp, pan');
state.geometry.ceilingZones=[];layers.ceiling.locked=false;layers.ceiling.visible=true;
state.world.x=0;state.world.y=0;
addCeilingZone({x:250,y:250});
assert.equal(state.geometry.ceilingZones.length,1);
assert.equal(state.geometry.ceilingZones[0].heightMm,2700);
assert.equal(state.geometry.ceilingZones[0].points.length,4);
assert.equal(state.selected.kind,'ceiling');
assert.equal(nearestElement({x:140,y:170}).kind,'ceiling','Ceiling border is selectable');
assert.equal(nearestElement({x:250,y:250})?.kind,'ceiling','Ceiling interior is draggable');
state.moving={start:{x:250,y:250},started:true,geometry:JSON.parse(JSON.stringify(state.geometry))};
handleEditorMove({clientX:280,clientY:290,altKey:false});
assert.equal(state.geometry.ceilingZones[0].x,170);
assert.equal(state.geometry.ceilingZones[0].y,210);
state.moving={start:{x:390,y:370},handle:'vertex:2',started:true,geometry:JSON.parse(JSON.stringify(state.geometry))};
handleEditorMove({clientX:440,clientY:410,altKey:false});
assert.equal(state.geometry.ceilingZones[0].width,270);
assert.equal(state.geometry.ceilingZones[0].height,200);
state.tool='select';
handleEditorDown({clientX:280,clientY:210});
assert.equal(state.geometry.ceilingZones[0].points.length,5,'Side midpoint adds a new editable corner');
handleEditorMove({clientX:320,clientY:320,shiftKey:true});
assert.notEqual(state.geometry.ceilingZones[0].points[1].y,210,'New corner can be dragged diagonally');
deleteSelected();
assert.equal(state.geometry.ceilingZones.length,0);
console.log('PASS: polygon ceiling zone placement, movement, corners, 45-degree snap and deletion');
state.equipment=[];state.selected=null;layers.controller.locked=false;layers.controller.visible=true;
addEquipment({x:500,y:300},'camera_ceiling');
assert.equal(state.equipment[0].system,'cctv');
assert.equal(state.equipment[0].code,'КМ.1');
assert.equal(state.equipment[0].mount,'ceiling');
assert.equal(state.equipment[0].hostWallId,null,'Ceiling camera is not accidentally attached to a wall');
assert.equal(state.equipment[0].viewAngleDeg,90);
assert.equal(state.equipment[0].blindZone,70);
assert.equal(state.equipment[0].downTiltDeg,45);
assert.equal(state.equipment[0].blindZoneMode,'auto');
assert.ok(cameraAutoBlindZone({mountingHeight:2700,downTiltDeg:0,viewAngleDeg:90,viewRange:420})>0);
assert.equal(cameraAutoBlindZone({mountingHeight:2700,downTiltDeg:90,viewAngleDeg:90,viewRange:420}),0);
assert.equal(cameraPlanAngle({downTiltDeg:90,viewAngleDeg:90}),Math.PI*2);
state.moving={start:{x:555,y:300},handle:'rotation',started:false,equipment:JSON.parse(JSON.stringify(state.equipment)),geometry:JSON.parse(JSON.stringify(state.geometry))};
handleEditorMove({clientX:500,clientY:400,shiftKey:true});
assert.ok(Math.abs(state.equipment[0].rotation-Math.PI/2)<.001,'Camera direction handle snaps to 45-degree steps');
addEquipment({x:700,y:300},'camera_ceiling_bracket');
assert.equal(state.equipment[1].bracketLengthMm,200);
const blocked=cameraVisibilityPolygon({x:0,y:0,rotation:0,viewAngleDeg:20,viewRange:300},{walls:[{id:'B',x1:100,y1:-100,x2:100,y2:100}],doors:[],windows:[],columns:[]},20);
assert.ok(Math.abs(blocked[11].x-100)<.001,'Camera coverage stops at the nearest wall');
const coverage=cameraCoverageShape({x:0,y:0,rotation:0,viewAngleDeg:20,viewRange:300,blindZone:70},{walls:[],doors:[],windows:[],columns:[]},20);
assert.ok(Math.abs(Math.hypot(coverage.inner[10].x,coverage.inner[10].y)-70)<.001,'Camera coverage leaves the configured blind zone empty');
console.log('PASS: ceiling cameras with and without bracket, coverage defaults and direction handle');
state.geometry.doors=[{id:'D1',wallId:'W',x:100,y:0,width:48,rotation:0,accessPointCode:'ТД.1.1'}];
state.accessPoints=[{id:'AP-D1',code:'ТД.1.1',doorId:'D1',readerCount:1,corridorSide:1,status:'proposed'}];
state.equipment=[];state.selected=null;layers.controller.locked=false;
addEquipment({x:105,y:8},'reader');
assert.equal(state.equipment.length,1);
assert.equal(state.equipment[0].hostDoorId,'D1');
assert.equal(state.equipment[0].hostWallId,'W');
assert.equal(state.equipment[0].code,'СЧТ.1.1');
assert.equal(state.equipment[0].accessPointId,'AP-D1');
assert.equal(equipmentShownOnPlan(state.equipment[0]),false,'Door-node devices stay out of the overview');
const accessMarker=accessPointMarkerPosition(state.accessPoints[0]);
assert.equal(nearestElement({x:accessMarker.x,y:accessMarker.y}).kind,'door','Access-point symbol selects its architectural door');
state.accessPoints[0].corridorSide=-1;
assert.equal(accessPointMarkerPosition(state.accessPoints[0]).y,-accessMarker.y,'Access-point symbol follows the saved corridor side');
assert.equal(equipmentShownOnPlan({id:'EQ-C',type:'controller'}),true,'Standalone equipment stays on the overview');
state.selected={kind:'equipment',id:state.equipment[0].id};
deleteSelected();
assert.equal(state.equipment.length,0,'Selected equipment can be deleted');
console.log('PASS: SKUD placement, compact access-point selection and deletion');
const codedDoor={id:'D2',wallId:'W',x:200,y:0,width:48,rotation:0,accessPointCode:'ТД.2.3'};
assert.equal(normalizeAccessPointCode('td2.3'),'ТД.2.3');
state.accessPoints=[];
assignAccessPointToDoor(codedDoor,'ТД.2.3');
assert.equal(accessPointForDoor(codedDoor).code,'ТД.2.3');
assert.equal(projectEquipmentCode('reader',codedDoor),'СЧТ.2.3');
assert.equal(projectEquipmentCode('exit_button',codedDoor),'КВ.2.3');
assert.equal(projectEquipmentCode('emergency_release',codedDoor),'АВР.2.3');
assert.equal(projectEquipmentCode('door_contact',codedDoor),'МКД.2.3');
assert.equal(projectEquipmentCode('lock',codedDoor),'ЗМК.2.3');
assert.equal(projectEquipmentCode('junction_box',codedDoor),'КС.2.3');
assert.equal(projectEquipmentCode('controller',codedDoor),'КНТ.2');
assert.equal(projectEquipmentCode('power_supply',codedDoor),'БП.2');
assert.equal(projectEquipmentCode('door_closer',codedDoor),'ДОВ.2.3');
assert.equal(migrateEquipmentCode({type:'controller',code:'AR.7'}),'КНТ.7');
assert.equal(migrateEquipmentCode({type:'reader',code:'YK1.4'}),'СЧТ.1.4');
assert.equal(migrateEquipmentCode({type:'lock',code:'UG1.4'}),'ЗМК.1.4');
assert.equal(migrateEquipmentCode({type:'power_supply',code:'R7'}),'БП.7');
console.log('PASS: presentation equipment designations');
const html = fs.readFileSync(path.join(__dirname,'../static/index.html'),'utf8');
const ids = new Set([...html.matchAll(/id="([^"]+)"/g)].map(m=>m[1]));
document.querySelectorAll=()=>[];
const query=document.querySelector;
document.querySelector=id=>{
  assert.ok(id.startsWith('#') && ids.has(id.slice(1)),`Missing control ${id}`);
  return query(id);
};
context.window={addEventListener(){}};
vm.runInContext('bindInterface();',context);
console.log('PASS: all interface controls exist and event binding succeeds');
