const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const path = require('node:path');
const elements = new Map();
const document = {querySelector(id) {
  if (!elements.has(id)) elements.set(id, {checked:false, classList:{add(){},remove(){},toggle(){}},addEventListener(){}});
  return elements.get(id);
}};
const context = vm.createContext({document, URLSearchParams, location:{search:''}, setTimeout(){}, clearTimeout(){}});
const src = fs.readFileSync(path.join(__dirname,'../static/app-v2.js'),'utf8').replace(/start\(\);\s*$/, '');
vm.runInContext(src + '\nthis.api={state,layers,nearestElement,selectedEditable,handleEditorMove,bindCanvasNavigation,addEquipment,deleteSelected,normalizeAccessPointCode,projectEquipmentCode,normalizeImportedGeometry,importedGeometryTransform}; drawGeometry=()=>{};drawEquipment=()=>{};showGeometryCard=()=>{};',context);
const {state,layers,nearestElement,selectedEditable,handleEditorMove,bindCanvasNavigation,addEquipment,deleteSelected,normalizeAccessPointCode,projectEquipmentCode,normalizeImportedGeometry,importedGeometryTransform} = context.api;
state.project={floorPlan:{width:2650,height:1850}};
state.cadPreview={sourceBounds:{minX:100,minY:200,maxX:600,maxY:500},transform:{scale:4,padding:70}};
const cadPayload={version:2,canvas:{width:500,height:300},metadata:{coordinate_system:'source_cad',origin:{x:100,y:200}},walls:[{id:'CAD-W',type:'wall',x1:100,y1:200,x2:600,y2:500,thickness:13}],doors:[],windows:[]};
const aligned=normalizeImportedGeometry(cadPayload);
assert.deepEqual(JSON.parse(JSON.stringify(aligned.walls[0])),{id:'CAD-W',type:'wall',x1:70,y1:1780,x2:2070,y2:580,thickness:13},'Source CAD geometry uses the exact preview transform');
state.cadPreview=null;
const fitted=importedGeometryTransform(cadPayload);
assert.equal(fitted.mode,'fit-canvas');
assert.deepEqual(JSON.parse(JSON.stringify(fitted.point(100,200))),{x:70,y:1678},'Unbacked CAD geometry is fitted and Y-flipped');
const fittedEnd=fitted.point(600,500);
assert.equal(fittedEnd.x,2580);
assert.ok(Math.abs(fittedEnd.y-172)<1e-9,'Fitted CAD geometry reaches the opposite padded edge');
console.log('PASS: imported CAD geometry aligns with preview or fits the empty canvas');
state.geometry={walls:[{id:'W',type:'wall',x1:0,y1:0,x2:400,y2:0},{id:'W2',type:'wall',x1:0,y1:150,x2:400,y2:150}],doors:[],windows:[{id:'WIN',wallId:'W',x:100,y:0,width:72,rotation:0}]};
assert.equal(nearestElement({x:134,y:0}).kind,'window','Full width of window precedes wall');
layers.window.locked=true;
state.selected={kind:'wall',id:'W'};
assert.equal(selectedEditable(),false,'Host wall cannot move/delete a locked opening');
layers.window.locked=false;
assert.equal(selectedEditable(),true);
layers.wall.locked=true;
assert.equal(nearestElement({x:134,y:0}).kind,'window','Window stays editable on locked wall');
layers.window.visible=false;
assert.equal(nearestElement({x:134,y:0}),null,'Hidden openings cannot be selected');
layers.window.visible=true;
const handlers={};
state.app={canvas:{getBoundingClientRect:()=>({left:0,top:0}),setPointerCapture(){},addEventListener:(name,fn)=>handlers[name]=fn}};
state.world={x:0,y:0,position:{set(x,y){state.world.x=x;state.world.y=y;}}};
state.selected={kind:'window',id:'WIN'};
state.moving={start:{x:100,y:0},started:false,geometry:JSON.parse(JSON.stringify(state.geometry))};
handleEditorMove({clientX:200,clientY:140,altKey:false});
assert.equal(state.geometry.windows[0].wallId,'W','Default drag stays on host');
assert.equal(state.geometry.windows[0].x,200);
handleEditorMove({clientX:220,clientY:150,altKey:true});
assert.equal(state.geometry.windows[0].wallId,'W2','Alt transfers opening');
handleEditorMove({clientX:999,clientY:150,altKey:false});
assert.equal(state.geometry.windows[0].x,364,'Opening clamped within wall');
state.moving=null;
state.editorEnabled=true;state.tool='pan';
bindCanvasNavigation();
const before=JSON.stringify(state.geometry);
handlers.pointerdown({clientX:10,clientY:20,pointerId:1,button:0});
handlers.pointermove({clientX:60,clientY:90});
assert.equal(state.world.x,50);assert.equal(state.world.y,70);
handlers.pointerup();
assert.equal(state.dragging,false);
assert.equal(JSON.stringify(state.geometry),before,'Pan never changes geometry');
console.log('PASS: window priority, locks, host projection, Alt transfer, edge clamp, pan');
state.geometry.doors=[{id:'D1',wallId:'W',x:100,y:0,width:48,rotation:0,accessPointCode:'ТД.1.1'}];
state.equipment=[];state.selected=null;layers.controller.locked=false;
addEquipment({x:105,y:8},'reader');
assert.equal(state.equipment.length,1);
assert.equal(state.equipment[0].hostDoorId,'D1');
assert.equal(state.equipment[0].hostWallId,'W');
assert.equal(state.equipment[0].code,'YK1.1');
assert.equal(nearestElement({x:105,y:8}).kind,'equipment','Equipment has selection priority');
deleteSelected();
assert.equal(state.equipment.length,0,'Selected equipment can be deleted');
console.log('PASS: SKUD placement, door linking, selection and deletion');
const codedDoor={accessPointCode:'ТД.2.3'};
assert.equal(normalizeAccessPointCode('td2.3'),'ТД.2.3');
assert.equal(projectEquipmentCode('reader',codedDoor),'YK2.3');
assert.equal(projectEquipmentCode('exit_button',codedDoor),'BGV2.3');
assert.equal(projectEquipmentCode('emergency_release',codedDoor),'BGM2.3');
assert.equal(projectEquipmentCode('door_contact',codedDoor),'BGB2.3');
assert.equal(projectEquipmentCode('lock',codedDoor),'UG2.3');
assert.equal(projectEquipmentCode('junction_box',codedDoor),'КС2.3');
assert.equal(projectEquipmentCode('controller',codedDoor),'AR.2');
assert.equal(projectEquipmentCode('power_supply',codedDoor),'R2');
assert.equal(projectEquipmentCode('door_closer',codedDoor),'Поз.4 · ТД.2.3');
console.log('PASS: source-project equipment designations');
const html = fs.readFileSync(path.join(__dirname,'../static/index.html'),'utf8');
const ids = new Set([...html.matchAll(/id="([^"]+)"/g)].map(m=>m[1]));
document.querySelectorAll=()=>[];
const query=document.querySelector;
document.querySelector=id=>{
  assert.ok(id.startsWith('#') && ids.has(id.slice(1)),`Missing control ${id}`);
  return query(id);
};
context.window={addEventListener(){}};
vm.runInContext('bindInterface();',context);
console.log('PASS: all interface controls exist and event binding succeeds');
