const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const path = require('node:path');
const elements = new Map();
const document = {querySelector(id) {
  if (!elements.has(id)) elements.set(id, {checked:false,dataset:{},classList:{add(){},remove(){},toggle(){}},addEventListener(){}});
  return elements.get(id);
},querySelectorAll(){return[];}};
const context = vm.createContext({document, URLSearchParams, location:{search:''}, setTimeout(){}, clearTimeout(){}});
const src = fs.readFileSync(path.join(__dirname,'../static/app-v2.js'),'utf8').replace(/start\(\);\s*$/, '');
vm.runInContext(src + '\nthis.api={state,layers,nearestElement,selectedEditable,handleEditorDown,handleEditorMove,bindCanvasNavigation,addEquipment,addDoor,adjustSelectedDoorRotation,doorRotationHandlePoint,deleteSelected,normalizeAccessPointCode,projectEquipmentCode,normalizeImportedGeometry,importedGeometryTransform,drawStagingGeometry,drawDraft,drawingPoint,screenSize,visualWallStrokeWidth,doorReviewSummary,setDoorDetectionRun,setAllDoorCandidates,toggleDoorCandidate,undo,redo}; drawGeometry=()=>{};drawEquipment=()=>{};showGeometryCard=()=>{};drawDoorRecognition=()=>{};',context);
const {state,layers,nearestElement,selectedEditable,handleEditorMove,bindCanvasNavigation,addEquipment,addDoor,adjustSelectedDoorRotation,deleteSelected,normalizeAccessPointCode,projectEquipmentCode,normalizeImportedGeometry,importedGeometryTransform,drawStagingGeometry,drawDraft,drawingPoint,screenSize,visualWallStrokeWidth,setDoorDetectionRun,setAllDoorCandidates,toggleDoorCandidate} = context.api;
assert.deepEqual(JSON.parse(JSON.stringify(context.api.doorReviewSummary([{swing:'unknown'},{swing:'left'},{swing:'right'}]))),{total:3,pending:1,confirmed:2},'Door status distinguishes neutral openings from confirmed leaves');
assert.equal(visualWallStrokeWidth({thickness:13}),3.25,'Saved blue walls use the same thin stroke as staging');
state.scale=4;
assert.equal(screenSize(5),1.25,'Five screen pixels are converted to world units at the current zoom');
const draftStrokes=[],draftCircles=[];
context.PIXI={Graphics:class {moveTo(){return this;} lineTo(){return this;} stroke(options){draftStrokes.push(options.width);return this;} circle(x,y,radius){draftCircles.push(radius);return this;} fill(){return this;}}};
state.draftLayer={removeChildren(){},addChild(){}};state.draftStart={x:0,y:0};
drawDraft({x:100,y:0});
assert.deepEqual(draftStrokes,[1.25]);
assert.deepEqual(draftCircles,[2,2],'Both draft endpoints stay eight screen pixels at 400% zoom');
state.draftStart=null;state.draftCurrent=null;state.draftLayer=null;state.scale=1;
const stagingStyles=[];
context.PIXI={Graphics:class {moveTo(){return this;} lineTo(){return this;} stroke(options){stagingStyles.push({width:options.width,color:options.color});return this;}}};
state.stagingLayer={removeChildren(){},addChild(){}};
state.stagingGeometry={walls:[{type:'wall',x1:0,y1:0,x2:100,y2:0,thickness:13},{type:'partition',x1:0,y1:10,x2:100,y2:10,thickness:7},{type:'wall',reviewHint:'thin_parallel_pair',x1:0,y1:20,x2:100,y2:20,thickness:13}],doors:[],windows:[]};
drawStagingGeometry();
assert.deepEqual(stagingStyles,[{width:3.25,color:0xff9f43},{width:1.75,color:0x38dbd0},{width:3.25,color:0xf4d06f}],'Staging overlay is thin and distinguishes review hints from partitions');
state.stagingGeometry=null;state.stagingLayer=null;
state.project={floorPlan:{width:2650,height:1850}};
state.cadPreview={sourceBounds:{minX:100,minY:200,maxX:600,maxY:500},transform:{scale:4,padding:70}};
const cadPayload={version:2,canvas:{width:500,height:300},metadata:{coordinate_system:'source_cad',origin:{x:100,y:200}},walls:[{id:'CAD-W',type:'wall',x1:100,y1:200,x2:600,y2:500,thickness:13}],doors:[],windows:[]};
const aligned=normalizeImportedGeometry(cadPayload);
assert.deepEqual(JSON.parse(JSON.stringify(aligned.walls[0])),{id:'CAD-W',type:'wall',x1:70,y1:1780,x2:2070,y2:580,thickness:13},'Source CAD geometry uses the exact preview transform');
const alignedOpening=normalizeImportedGeometry({...cadPayload,doors:[{id:'D-CAD',wallId:'CAD-W',x:200,y:200,width:8,rotation:0,swing:'unknown'}]});
assert.equal(alignedOpening.doors[0].width,32,'CAD door gap width uses the same preview scale as its wall');
assert.equal(alignedOpening.doors[0].swing,'unknown');
const hinted=normalizeImportedGeometry({...cadPayload,walls:[{...cadPayload.walls[0],reviewHint:'thin_parallel_pair',pairedGapMm:100}]});
assert.equal(hinted.walls[0].reviewHint,'thin_parallel_pair');
assert.equal(hinted.walls[0].type,'wall','Review hint must not silently classify a partition');
const centerline=normalizeImportedGeometry({...cadPayload,metadata:{...cadPayload.metadata,k:.1},walls:[{...cadPayload.walls[0],id:'CAD-W-CL',source:'cad_face_pair_centerline',pairedGapMm:100}]});
assert.equal(centerline.walls[0].thickness,4,'CAD pair gap is transformed into physical editor thickness');
state.cadPreview=null;
const fitted=importedGeometryTransform(cadPayload);
assert.equal(fitted.mode,'fit-canvas');
assert.deepEqual(JSON.parse(JSON.stringify(fitted.point(100,200))),{x:70,y:1678},'Unbacked CAD geometry is fitted and Y-flipped');
const fittedEnd=fitted.point(600,500);
assert.equal(fittedEnd.x,2580);
assert.ok(Math.abs(fittedEnd.y-172)<1e-9,'Fitted CAD geometry reaches the opposite padded edge');
console.log('PASS: imported CAD geometry aligns with preview or fits the empty canvas');
state.geometry={walls:[{id:'W',type:'wall',x1:0,y1:0,x2:400,y2:0},{id:'W2',type:'wall',x1:0,y1:150,x2:400,y2:150}],doors:[],windows:[{id:'WIN',wallId:'W',x:100,y:0,width:72,rotation:0}]};
assert.equal(nearestElement({x:134,y:0}).kind,'window','Full width of window precedes wall');
layers.window.locked=true;
state.selected={kind:'wall',id:'W'};
assert.equal(selectedEditable(),false,'Host wall cannot move/delete a locked opening');
layers.window.locked=false;
assert.equal(selectedEditable(),true);
layers.wall.locked=true;
assert.equal(nearestElement({x:134,y:0}).kind,'window','Window stays editable on locked wall');
layers.window.visible=false;
assert.equal(nearestElement({x:134,y:0}),null,'Hidden openings cannot be selected');
layers.window.visible=true;
const handlers={};
state.app={canvas:{getBoundingClientRect:()=>({left:0,top:0}),setPointerCapture(){},addEventListener:(name,fn)=>handlers[name]=fn}};
state.world={x:0,y:0,position:{set(x,y){state.world.x=x;state.world.y=y;}}};
document.querySelector('#snap-toggle').checked=false;state.scale=1;state.draftStart={x:0,y:0};
assert.deepEqual(JSON.parse(JSON.stringify(drawingPoint({clientX:103,clientY:37,shiftKey:false}))),{x:103,y:37},'Free drawing follows the pointer without a default grid');
const constrained=drawingPoint({clientX:103,clientY:37,shiftKey:true});assert.ok(Math.abs(constrained.y)<1e-9,'Shift constrains a wall to the nearest 45-degree direction');
document.querySelector('#snap-toggle').checked=true;
assert.deepEqual(JSON.parse(JSON.stringify(drawingPoint({clientX:103,clientY:37,shiftKey:false}))),{x:100,y:40},'Optional grid snapping remains available');
document.querySelector('#snap-toggle').checked=false;state.draftStart=null;
state.scale=1;layers.wall.locked=false;state.equipment=[];state.savedGeometry=JSON.parse(JSON.stringify(state.geometry));state.savedEquipment=[];
state.selected={kind:'wall',id:'W'};state.tool='select';
context.api.handleEditorDown({clientX:400,clientY:0});
assert.equal(state.resizingWall.endpoint,'end','Clicking the visible endpoint starts wall resizing');
handleEditorMove({clientX:500,clientY:100,altKey:false});
assert.deepEqual({x2:state.geometry.walls[0].x2,y2:state.geometry.walls[0].y2},{x2:500,y2:100},'Wall endpoint follows the pointer');
assert.deepEqual({x:state.geometry.windows[0].x,y:state.geometry.windows[0].y},{x:125,y:25},'Hosted opening keeps its relative position on the resized wall');
state.resizingWall=null;state.geometry={walls:[{id:'W',type:'wall',x1:0,y1:0,x2:400,y2:0},{id:'W2',type:'wall',x1:0,y1:150,x2:400,y2:150}],doors:[],windows:[{id:'WIN',wallId:'W',x:100,y:0,width:72,rotation:0}]};
state.selected={kind:'window',id:'WIN'};
state.moving={start:{x:100,y:0},started:false,geometry:JSON.parse(JSON.stringify(state.geometry))};
handleEditorMove({clientX:200,clientY:140,altKey:false});
assert.equal(state.geometry.windows[0].wallId,'W','Default drag stays on host');
assert.equal(state.geometry.windows[0].x,200);
handleEditorMove({clientX:220,clientY:150,altKey:true});
assert.equal(state.geometry.windows[0].wallId,'W2','Alt transfers opening');
handleEditorMove({clientX:999,clientY:150,altKey:false});
assert.equal(state.geometry.windows[0].x,364,'Opening clamped within wall');
state.moving=null;
state.editorEnabled=true;state.tool='pan';
bindCanvasNavigation();
const before=JSON.stringify(state.geometry);
handlers.pointerdown({clientX:10,clientY:20,pointerId:1,button:0});
handlers.pointermove({clientX:60,clientY:90});
assert.equal(state.world.x,50);assert.equal(state.world.y,70);
handlers.pointerup();
assert.equal(state.dragging,false);
assert.equal(JSON.stringify(state.geometry),before,'Pan never changes geometry');
console.log('PASS: window priority, locks, host projection, Alt transfer, edge clamp, pan');
state.world.x=0;state.world.y=0;state.scale=1;
state.geometry={walls:[{id:'W',type:'wall',x1:0,y1:0,x2:220,y2:0},{id:'W3',type:'wall',x1:300,y1:0,x2:300,y2:220}],doors:[],windows:[]};
state.equipment=[];state.savedGeometry=JSON.parse(JSON.stringify(state.geometry));state.savedEquipment=[];state.tool='door-manual';
addDoor({x:100,y:8},'unknown',1,true);
assert.equal(state.geometry.doors.length,1);
assert.deepEqual(JSON.parse(JSON.stringify(state.selected)),{kind:'door',id:state.geometry.doors[0].id},'Manual door is selected immediately');
assert.equal(state.tool,'select','Manual placement returns to correction mode');
state.tool='door-left';
context.api.handleEditorDown({clientX:100,clientY:0});
assert.equal(state.geometry.doors.length,1,'Clicking an existing door in placement mode must not create a duplicate');
assert.equal(state.tool,'select','Existing door capture leaves placement mode');
assert.equal(state.selected.kind,'door');
assert.equal(state.selected.id,state.geometry.doors[0].id);
adjustSelectedDoorRotation('rotate-right');
assert.ok(Math.abs(state.geometry.doors[0].rotation-Math.PI/2)<1e-9,'Door rotates exactly 90 degrees');
state.geometry.doors[0].rotation=0;state.geometry.doors[0].openingSide=-1;state.selected={kind:'door',id:state.geometry.doors[0].id};state.tool='select';
const rotateHandle=context.api.doorRotationHandlePoint(state.geometry.doors[0]);
context.api.handleEditorDown({clientX:rotateHandle.x,clientY:rotateHandle.y});
assert.ok(state.rotating,'Visible rotation handle starts mouse rotation');
handleEditorMove({clientX:160,clientY:0,altKey:false});
assert.ok(Math.abs(state.geometry.doors[0].rotation-Math.PI/2)<1e-9,'Dragging the rotation handle rotates around the door center');
state.rotating=null;
state.moving={start:{x:100,y:0},started:false,geometry:JSON.parse(JSON.stringify(state.geometry)),equipment:[]};
handleEditorMove({clientX:300,clientY:80,altKey:false});
assert.equal(state.geometry.doors[0].wallId,'W3','Door drag snaps to a different angled wall without a modifier key');
assert.equal(state.geometry.doors[0].x,300);
assert.equal(state.geometry.doors[0].y,80);
assert.ok(Math.abs(Math.abs(state.geometry.doors[0].rotation)-Math.PI)<1e-9,'Manual quarter-turn is preserved on the new wall');
let contextPrevented=false;handlers.contextmenu({preventDefault(){contextPrevented=true;}});
assert.equal(contextPrevented,true);
assert.equal(state.selected,null,'Right click fixes the adjusted door and clears selection');
console.log('PASS: manually placed door is selected, movable between walls, and rotatable');
state.geometry.doors=[{id:'D1',wallId:'W',x:100,y:0,width:48,rotation:0,accessPointCode:'ТД.1.1'}];
state.equipment=[];state.selected=null;layers.controller.locked=false;
addEquipment({x:105,y:8},'reader');
assert.equal(state.equipment.length,1);
assert.equal(state.equipment[0].hostDoorId,'D1');
assert.equal(state.equipment[0].hostWallId,'W');
assert.equal(state.equipment[0].code,'YK1.1');
assert.equal(nearestElement({x:105,y:8}).kind,'equipment','Equipment has selection priority');
deleteSelected();
assert.equal(state.equipment.length,0,'Selected equipment can be deleted');
console.log('PASS: SKUD placement, door linking, selection and deletion');
const codedDoor={accessPointCode:'ТД.2.3'};
assert.equal(normalizeAccessPointCode('td2.3'),'ТД.2.3');
assert.equal(projectEquipmentCode('reader',codedDoor),'YK2.3');
assert.equal(projectEquipmentCode('exit_button',codedDoor),'BGV2.3');
assert.equal(projectEquipmentCode('emergency_release',codedDoor),'BGM2.3');
assert.equal(projectEquipmentCode('door_contact',codedDoor),'BGB2.3');
assert.equal(projectEquipmentCode('lock',codedDoor),'UG2.3');
assert.equal(projectEquipmentCode('junction_box',codedDoor),'КС2.3');
assert.equal(projectEquipmentCode('controller',codedDoor),'AR.2');
assert.equal(projectEquipmentCode('power_supply',codedDoor),'R2');
assert.equal(projectEquipmentCode('door_closer',codedDoor),'Поз.4 · ТД.2.3');
console.log('PASS: source-project equipment designations');
const persisted={version:2,canvas:{},walls:[{id:'W-SAVED',type:'wall',x1:0,y1:0,x2:100,y2:0,thickness:13}],doors:[],windows:[]};
state.savedGeometry=JSON.parse(JSON.stringify(persisted));state.savedEquipment=[];
state.geometry={...JSON.parse(JSON.stringify(persisted)),doors:[{id:'D-TEMP',wallId:'W-SAVED',x:50,y:0,width:48}]};state.equipment=[];
state.history=[{geometry:JSON.parse(JSON.stringify(persisted)),equipment:[]}];state.future=[];
context.api.undo();
assert.equal(state.dirty,false,'Undoing a test door back to saved geometry clears unsaved status');
assert.equal(state.equipmentDirty,false,'A geometry undo must not mark unchanged equipment dirty');
assert.equal(document.querySelector('#save-geometry').disabled,true);
context.api.redo();assert.equal(state.dirty,true);
context.api.undo();assert.equal(state.dirty,false);
console.log('PASS: undo/redo dirty state matches saved geometry');
setDoorDetectionRun({run_id:'RUN',candidates:[{candidate_id:'C1',x:100,y:100,width:60,rotation:0},{candidate_id:'C2',x:200,y:100,width:60,rotation:0}]});
assert.equal(state.doorCandidateSelection.size,2,'New recognition run selects every candidate initially');
assert.equal(document.querySelector('#door-accept-candidates').textContent,'Принять выбранные: 2');
setAllDoorCandidates(false);
assert.equal(state.doorCandidateSelection.size,0);
assert.equal(document.querySelector('#door-accept-candidates').disabled,true);
assert.equal(document.querySelector('#door-candidate-count').textContent,'Найдено 2 · выбрано 0 · исключено 2');
setAllDoorCandidates(true);
assert.equal(state.doorCandidateSelection.size,2);
assert.equal(toggleDoorCandidate({x:128,y:104}),true,'Any visible part of a candidate is clickable');
assert.equal(state.doorCandidateSelection.has('C1'),false);
console.log('PASS: recognition candidates can be selected and excluded as a batch');
const html = fs.readFileSync(path.join(__dirname,'../static/index.html'),'utf8');
const ids = new Set([...html.matchAll(/id="([^"]+)"/g)].map(m=>m[1]));
document.querySelectorAll=()=>[];
const query=document.querySelector;
document.querySelector=id=>{
  assert.ok(id.startsWith('#') && ids.has(id.slice(1)),`Missing control ${id}`);
  return query(id);
};
context.window={addEventListener(){}};
vm.runInContext('bindInterface();',context);
console.log('PASS: all interface controls exist and event binding succeeds');
